name: Test and Build

on:
  push:
    branches: [test]
  pull_request:
    branches: [test]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
        continue-on-error: true

      - name: Format check
        run: npx prettier --check "src/**/*.{js,jsx,ts,tsx,json,css,md}"
        continue-on-error: true 

      - name: GraphQL Codegen
        run: npm run codegen
        continue-on-error: true

      - name: Build
        run: npm run build
        continue-on-error: true 

      - name: Run Jest tests
        run: npm run test
        continue-on-error: true  

      - name: Run E2E tests
        run: npm run test:e2e:ci
        continue-on-error: true  

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        continue-on-error: true  
